
# rm(list=ls())

library(ineqx)
library(stringr)

dat1 <-
  crDat(2, 3, c("10", "10", "10"), "10+10*(group==1)*x+250*(group==2)*x+300*(group==3)*x*year", "0.1", "between", X_const = T, seed=T, sav=F)

dat2 <-
  crDat(2, 3, c("10", "10", "10"), "10+10*(group==1)*x+250*(group==2)*x+300*(group==3)*x*year", "0.1", "within", X_const = T, seed=T, sav=F)


test <- ineqx(x="c3.x", y="inc", ystat="CV2", groupvar = "group", timevar = "i.year", cf=1, dat = dat1)

test$dT[[1]]

plot(test, type = "dPA")

wibe(y="inc", groupvar = "group", timevar = "year", dat=dat1)[[2]] %>% dplyr::mutate(dCV2W=CV2W-first(CV2W),
                                                                                     dCV2B=CV2B-first(CV2B),
                                                                                     dCV2T=CV2T-first(CV2T),
                                                                                     dsum1=dCV2B+dCV2W,
                                                                                     dVarB=VarB-first(VarB),
                                                                                     dVarW=VarW-first(VarW),
                                                                                     dsum2=dVarB+dVarW,
                                                                                     dVarT=VarT-first(VarT))


27640


# -> within-variance with X_type == between is also generated by variation in x

lm1 <- lm(inc ~ -1 + x * (as.factor(group) * as.factor(year)), data = dat1)
summary(lm1) # correct (when not including time)

lm2 <- lm1
lm2$coefficients["x:as.factor(group)3:as.factor(year)2"] <- 0
lm2$coefficients["x:as.factor(group)2:as.factor(year)2"] <- 0
lm2$coefficients["as.factor(group)3:as.factor(year)2"] <- 0
lm2$coefficients["as.factor(group)2:as.factor(year)2"] <- 0
lm2$coefficients["x:as.factor(year)2"] <- 0
lm2$coefficients["as.factor(year)2"] <- 0




crMeans <- function(pred, yr) {
  return(dat1 %>% dplyr::mutate(yhat=pred) %>% dplyr::filter(year==yr) %>% group_by(group) %>% dplyr::summarise(yhat=mean(yhat)) %>% .$yhat)
}

crVar <- function(pred, yr) {
  return(dat1 %>% dplyr::mutate(yhat=pred) %>% dplyr::filter(year==yr) %>% group_by(group) %>% dplyr::mutate(yhat=mean(yhat), res=inc-yhat) %>% dplyr::summarise(yhat=var(res)) %>% .$yhat)
}




#xb
mu22  <- crMeans(predict(lm1, newdata = dat1), 2)
sig22 <- crVar(predict(lm1, newdata = dat1), 2)


mu11 <- crMeans(predict(lm1, newdata = dat1), 1)
sig11 <- crVar(predict(lm1, newdata = dat1), 1)

mu21 <- crMeans(predict(lm2, newdata = dat1), 2)  # beta constant == effect of X
mu12 <- crMeans(predict(lm1, newdata = dat1 %>% dplyr::mutate(x=rep(dat1 %>% dplyr::filter(year==1) %>% .$x, 2))), 2) # X constant == effect of beta

n <- c(1000,1000,1000)


# Descriptive

dat1 %>% dplyr::mutate(yhat=predict(lm1, type = "response", data = dat1)) %>% group_by(year, group) %>% dplyr::summarise(yhat=mean(yhat))



# -----------------

# sum(1/3*((mu22 - mean(mu22))^2 + sig22)/mean(mu22)) - sum(1/3*((mu11 - mean(mu11))^2 + sig11)/mean(mu11))


VarB(n, mu22) - VarB(n, mu11)

I <- VarB(n, mu22) - VarB(n, mu11) - (VarB(n, mu12) - VarB(n, mu11) + VarB(n, mu21) - VarB(n, mu11))

# coefficient effect + characteristics effect + interaction
(VarB(n, mu12) - VarB(n, mu11) + VarB(n, mu21) - VarB(n, mu11)) + I

CV2B(n, mu22) - CV2B(n, mu11) # predicted change

CV2B(n, mu22) - CV2B(n,  mu12) + CV2B(n, mu22) - CV2B(n,  mu21)  # predicted change due to x from perspective t2

CV2B(n, mu12) - CV2B(n,  mu11) + CV2B(n, mu21) - CV2B(n,  mu11) # predicted change due to x from perspective t1




(
  CV2B(n, mu22) - CV2B(n,  mu11) + CV2B(n, mu22) - CV2B(n,  mu11) - CV2B(n,  mu21) + CV2B(n, mu21) - CV2B(n,  mu12) + CV2B(n, mu12)
)/2



dydx_t1 <- CV2B(n.cf, x, beta) - CV2B(n.cf, mu.cf)
dydx_t0 <- CV2B(n.cf, mu.cf + beta.cf)   - CV2B(n.cf, mu.cf)

delta[i] <- dydx_t1 - dydx_t0



