


library(ineqx)
library(stringr)

dat1 <-
  crDat(2, 3, c("1000", "1000", "1000"), "10+10*(group==1)*x+250*(group==2)*x*year*year*year+100*(group==3)*x*year-500*z*(group==3)*year", "0", "between", seed=F, sav=F)

dat1 <-
  dat1 %>%
  dplyr::mutate(x=c(dat1 %>% dplyr::filter(year==1) %>% .$x, {dat1 %>% dplyr::filter(year==2) %>% .$x}))

# -> within-variance with X_type == between is also generated by variation in x

lm1 <- lm(inc ~ -1 + x * (as.factor(group) * as.factor(year)), data = dat1)
summary(lm1) # correct (when not including time)

lm2 <- lm1
lm2$coefficients["x:as.factor(group)3:as.factor(year)2"] <- 0
lm2$coefficients["x:as.factor(group)2:as.factor(year)2"] <- 0
lm2$coefficients["as.factor(group)3:as.factor(year)2"] <- 0
lm2$coefficients["as.factor(group)2:as.factor(year)2"] <- 0
lm2$coefficients["x:as.factor(year)2"] <- 0
lm2$coefficients["as.factor(year)2"] <- 0




crMeans <- function(pred, yr) {
  return(dat1 %>% dplyr::mutate(yhat=pred) %>% dplyr::filter(year==yr) %>% group_by(group) %>% dplyr::summarise(yhat=mean(yhat)) %>% .$yhat)
}


#xb
mu22 <- crMeans(predict(lm1, newdata = dat1), 2)
mu11 <- crMeans(predict(lm1, newdata = dat1), 1)

mu21 <- crMeans(predict(lm2, newdata = dat1), 2)  # beta constant
mu12 <- crMeans(predict(lm1, newdata = dat1 %>% dplyr::mutate(x=rep(dat1 %>% dplyr::filter(year==1) %>% .$x, 2))), 2) # X constant

n <- c(1000,1000,1000)


# Descriptive

dat1 %>% dplyr::mutate(yhat=predict(lm1, type = "response", data = dat1)) %>% group_by(year, group) %>% dplyr::summarise(yhat=mean(yhat))

wibe(y="inc", groupvar = "group", timevar = "year", dat=dat1)[[2]] %>% dplyr::mutate(dCV2B=CV2B-first(CV2B))


# -----------------


CV2B(n, mu22) - CV2B(n, mu11) # predicted change

( (CV2B(n, mu22) - CV2B(n,  mu12) + CV2B(n, mu22) - CV2B(n,  mu21)) ) # predicted change due to x
# dYdX                            + dYdD

(CV2B(n, mu22) - CV2B(n, mu11)) - ((CV2B(n, mu22) - CV2B(n,  mu21)) + (CV2B(n, mu22) - CV2B(n,  mu12))) # other factors






summary(dat1 %>% filter(group==1) %>% .$x)
summary(dat1 %>% filter(group==2) %>% .$x)
summary(dat1 %>% filter(group==3) %>% .$x)




# t1 <- ineqx(x="c3.x", xpv = c(0,1), y="inc", ystat="Var", groupvar = "i.group", timevar = "i.year", cf=1, dat = dat1)
# plot(t1, type="dPA")
